spring:
  cloud:
    gateway:
      routes:
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/items/**,/search/**
        - id: hm-cart
          uri: lb://hm-cart
          predicates:
            - Path=/carts/**
        - id: hm-pay
          uri: lb://hm-pay
          predicates:
            - Path=/pay-orders/**
        - id: hm-trade
          uri: lb://hm-trade
          predicates:
            - Path=/orders/**
        - id: hm-user
          uri: lb://hm-user
          predicates:
            - Path=/users/**,/addresses/**

docker run --name seata \
-p 8099:8099 \
-p 7099:7099 \
-e SEATA_IP=117.72.198.60 \
-v ./seata:/seata-server/resources \
--privileged=true \
--network leadnews_network \
-d \
seataio/seata-server